# Generated by Django 5.2.6 on 2025-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/images/', verbose_name='Foto de cédula o selfie'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdf/', verbose_name='Documento PDF validado'),
        ),
    ]
