# Generated by Django 4.2.25 on 2025-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de Ayuda', 'verbose_name_plural': 'Solicitudes de Ayuda'},
        ),
        migrations.AddField(
            model_name='help',
            name='category',
            field=models.CharField(default='General', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='help',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('closed', 'Cerrada')], default='active', max_length=10),
        ),
    ]
