# Generated by Django 4.2.25 on 2025-10-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_help_options_help_category_help_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('donacion', 'Donación'), ('comunidad', 'Comunidad'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Categoría'),
        ),
    ]
