# Generated by Django 4.2.25 on 2025-10-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_help_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='date',
        ),
        migrations.AddField(
            model_name='help',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='help',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto solicitado'),
        ),
        migrations.AddField(
            model_name='help',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='help',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('donacion', 'Donación'), ('dinero', 'Dinero'), ('alimentos', 'Alimentos'), ('comunidad', 'Comunidad'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Categoría'),
        ),
    ]
