# Generated by Django 4.2.25 on 2025-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_remove_help_date_help_account_number_help_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
    ]
