# Generated by Django 4.2.25 on 2025-11-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_alter_help_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('closed', 'Cerrada')], default='active', max_length=10),
        ),
        migrations.DeleteModel(
            name='RequestVolunteer',
        ),
    ]
