# Generated by Django 4.2.25 on 2025-11-02 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0006_alter_help_status_delete_requestvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_helps', to=settings.AUTH_USER_MODEL),
        ),
    ]
