# Generated by Django 5.2.6 on 2025-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_alter_help_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('accepted', 'Aceptada'), ('closed', 'Cerrada')], default='pending', max_length=10),
        ),
    ]
