# Generated by Django 5.2.6 on 2025-11-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_alter_help_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='help',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='help',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='help',
            name='lng',
        ),
        migrations.AddField(
            model_name='help',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='help',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de contacto'),
        ),
        migrations.AddField(
            model_name='help',
            name='dni_copy',
            field=models.ImageField(blank=True, null=True, upload_to='helps/dni/', verbose_name='Copia de cédula'),
        ),
        migrations.AddField(
            model_name='help',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='helps/images/', verbose_name='Fotografía o evidencia'),
        ),
        migrations.AddField(
            model_name='help',
            name='evidence_pdf',
            field=models.FileField(blank=True, null=True, upload_to='helps/pdf/', verbose_name='Documento de respaldo (PDF)'),
        ),
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('closed', 'Cerrada')], default='active', max_length=10),
        ),
    ]
