# Generated by Django 5.2.6 on 2025-11-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_remove_help_account_number_remove_help_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participación', 'verbose_name_plural': 'Participaciones'},
        ),
        migrations.RemoveField(
            model_name='help',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='help',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='help',
            name='dni_copy',
        ),
        migrations.RemoveField(
            model_name='help',
            name='evidence_image',
        ),
        migrations.RemoveField(
            model_name='help',
            name='evidence_pdf',
        ),
        migrations.AddField(
            model_name='help',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='help',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto solicitado'),
        ),
        migrations.AddField(
            model_name='help',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='help',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('accepted', 'Aceptada'), ('closed', 'Cerrada')], default='active', max_length=10),
        ),
    ]
