# Generated by Django 5.2.6 on 2025-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_alter_participation_options_remove_help_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='account_number',
        ),
        migrations.AddField(
            model_name='help',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='help',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de contacto'),
        ),
        migrations.AddField(
            model_name='help',
            name='dni_copy',
            field=models.ImageField(blank=True, null=True, upload_to='helps/dni/', verbose_name='Copia de cédula'),
        ),
        migrations.AddField(
            model_name='help',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='helps/images/', verbose_name='Fotografía o evidencia'),
        ),
        migrations.AddField(
            model_name='help',
            name='evidence_pdf',
            field=models.FileField(blank=True, null=True, upload_to='helps/pdf/', verbose_name='Documento de respaldo (PDF)'),
        ),
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('accepted', 'Aceptada'), ('closed', 'Cerrada')], default='pending', max_length=10),
        ),
    ]
