# Generated by Django 5.2.6 on 2025-11-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_remove_help_account_number_help_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto donado')),
                ('payment_method', models.CharField(default='manual', max_length=30, verbose_name='Método de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Donante')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='volunteers.help', verbose_name='Solicitud de ayuda')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
