# Generated by Django 5.2.6 on 2025-11-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('closed', 'Cerrada')], default='pending', max_length=10),
        ),
    ]
