# Generated by Django 6.0.2 on 2026-03-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0016_alter_help_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('accepted', 'Aceptada'), ('resubmit', 'Pendiente de Reenvío'), ('closed', 'Cerrada')], default='pending', max_length=10),
        ),
    ]
